
background=NO

# Disable anonymous login
anonymous_enable=NO

# Allow local Linux users to login
local_enable=YES

# Allow write operations
write_enable=YES

# Jail user in their home directory
chroot_local_user=YES

# Set home directory to WordPress volume
local_root=/var/www/html

# Enable passive mode
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# Passive mode address
pasv_address=${DOMAIN_NAME}

# Disable active mode
port_enable=NO

# Enable logging
xferlog_enable=YES

seccomp_sandbox=NO
allow_writeable_chroot=YES
